#!/usr/bin/env python3
# SPDX-FileCopyrightText: toybox.py contributors
#
# SPDX-License-Identifier: MIT

"""Rewrite the README's toybox table from toybox/toystore.py.

    tools/gen_store_table.py            rewrite README.md in place
    tools/gen_store_table.py --check    exit 1 if it is out of date (for CI)

The table and the index used to be two hand-kept lists that knew nothing about each
other, which is exactly how documentation drifts from behaviour. Now there is one
dataset and the table is derived from it.
"""

import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from toybox.toystore import KNOWN, REJECTED    # noqa: E402

BEGIN = '<!-- BEGIN store table (generated by tools/gen_store_table.py) -->'
END = '<!-- END store table -->'


def _title(key: str) -> str:
    return key.split('/')[1]


def render() -> str:
    lines = [BEGIN,
             '',
             '| Toybox | Add with | Provides |',
             '|---|---|---|']

    for key in sorted(KNOWN, key=lambda k: _title(k).lower()):
        entry = KNOWN[key]
        provides = entry.get('provides', '')

        extras = []
        if entry.get('kind') == 'c':
            extras.append('**C toybox**')
        if entry.get('global'):
            extras.append('imported as `' + entry['global'] + '`')
        if entry.get('note'):
            extras.append(entry['note'])
        if extras:
            provides += ' — ' + '; '.join(extras)

        lines.append('| [' + _title(key) + '](https://github.com/' + key + ') | `toybox add ' + key + '` | ' + provides + ' |')

    lines += ['',
              'Browse the same data from the command line with `toybox store content`, and get',
              'the detail for one entry — including how it is imported — with `toybox store info',
              '<name>`.',
              '']

    if REJECTED:
        lines += ['<details>',
                  '<summary>Checked and <b>not</b> usable as toyboxes (' + str(len(REJECTED)) + ')</summary>',
                  '',
                  'Recorded so the reasoning is not re-derived. See `toybox store info <name>`.',
                  '']
        for key in sorted(REJECTED):
            lines.append('- **[' + _title(key) + '](https://github.com/' + key + ')** — ' + REJECTED[key])
        lines += ['', '</details>', '']

    lines.append(END)
    return '\n'.join(lines)


def main() -> int:
    readme = Path(__file__).resolve().parent.parent / 'README.md'
    text = readme.read_text()

    if BEGIN not in text or END not in text:
        print('error: README.md has no store-table markers; add ' + BEGIN, file=sys.stderr)
        return 2

    updated = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END), lambda _: render(),
                     text, flags=re.S)

    if '--check' in sys.argv:
        if updated != text:
            print('README store table is out of date — run tools/gen_store_table.py', file=sys.stderr)
            return 1
        print('README store table is up to date (' + str(len(KNOWN)) + ' entries).')
        return 0

    readme.write_text(updated)
    print('wrote ' + str(len(KNOWN)) + ' entries into README.md')
    return 0


if __name__ == '__main__':
    sys.exit(main())
